//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web;

    public partial class bangDiem
    {
        public int id { get; set; }
        public Nullable<int> fk_giaoChiTieu { get; set; }
        public Nullable<int> diemCoDinh { get; set; }
        public Nullable<int> diemChiDoan { get; set; }
        public Nullable<int> diemThanhDoan { get; set; }
        public Nullable<int> diemTinhDoan { get; set; }
        public string ycMinhChung { get; set; }
        public Nullable<System.DateTime> thoiGian { get; set; }
        public string yKienPhanHoi { get; set; }
        public string banPhuTrach { get; set; }
        public byte[] hinhAnh { get; set; }
        public Nullable<int> trangThai { get; set; }
        public HttpPostedFileBase HinhAnhFile { get; set; }

        public virtual giaoChiTieuchoDV giaoChiTieuchoDV { get; set; }
    }
}
