//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class chamdiemEntities : DbContext
    {
        public chamdiemEntities()
            : base("name=chamdiemEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<chiTietChiTieu> chiTietChiTieux { get; set; }
        public virtual DbSet<chiTieu> chiTieux { get; set; }
        public virtual DbSet<dm_donVi> dm_donVi { get; set; }
        public virtual DbSet<donVi> donVis { get; set; }
        public virtual DbSet<nguoiDung> nguoiDungs { get; set; }
        public virtual DbSet<nhomChiTieu> nhomChiTieux { get; set; }
        public virtual DbSet<taiKhoan> taiKhoans { get; set; }
        public virtual DbSet<bangDiem> bangDiems { get; set; }
        public virtual DbSet<giaoChiTieuchoDV> giaoChiTieuchoDVs { get; set; }
        public virtual DbSet<quanHeDonVi> quanHeDonVis { get; set; }
        public virtual DbSet<loaiTieuChi> loaiTieuChis { get; set; }
    }
}
