//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class chiTieu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public chiTieu()
        {
            this.chiTietChiTieux = new HashSet<chiTietChiTieu>();
            this.giaoChiTieuchoDVs = new HashSet<giaoChiTieuchoDV>();
        }
    
        public int iD { get; set; }
        public string ten { get; set; }
        public Nullable<int> fk_loaiChiTieu { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<chiTietChiTieu> chiTietChiTieux { get; set; }
        public virtual nhomChiTieu nhomChiTieu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<giaoChiTieuchoDV> giaoChiTieuchoDVs { get; set; }
    }
}
