//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class giaoChiTieuchoDV
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public giaoChiTieuchoDV()
        {
            this.bangDiems = new HashSet<bangDiem>();
        }
    
        public int id { get; set; }
        public Nullable<int> fk_chiTieu { get; set; }
        public Nullable<int> fk_dmDonViChiDoan { get; set; }
        public Nullable<int> fk_dmDonViThanhDoan { get; set; }
        public Nullable<int> fk_dmDonViTinhDoan { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<bangDiem> bangDiems { get; set; }
        public virtual chiTieu chiTieu { get; set; }
        public virtual dm_donVi dm_donVi { get; set; }
        public virtual dm_donVi dm_donVi1 { get; set; }
        public virtual dm_donVi dm_donVi2 { get; set; }
    }
}
