//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class nhomChiTieu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public nhomChiTieu()
        {
            this.chiTieux = new HashSet<chiTieu>();
        }
    
        public int iD { get; set; }
        public string ten { get; set; }
        public int tongDiem { get; set; }
        public Nullable<int> fk_loaiTieuChi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<chiTieu> chiTieux { get; set; }
        public virtual loaiTieuChi loaiTieuChi { get; set; }
    }
}
