//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class quanHeDonVi
    {
        public int iD { get; set; }
        public Nullable<int> donViCha { get; set; }
        public Nullable<int> donViCon { get; set; }
    
        public virtual dm_donVi dm_donVi { get; set; }
        public virtual dm_donVi dm_donVi1 { get; set; }
    }
}
